export const SIGNALING_ERROR_CODES = {
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_FULL: "ROOM_FULL",
  ROOM_EXPIRED: "ROOM_EXPIRED",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  HOST_RECONNECT_WINDOW_EXPIRED: "HOST_RECONNECT_WINDOW_EXPIRED",
  RECONNECT_TOKEN_STALE: "RECONNECT_TOKEN_STALE",
  PASSWORD_VERSION_MISMATCH: "PASSWORD_VERSION_MISMATCH",
  RATE_LIMITED: "RATE_LIMITED",
  INVALID_SIGNAL_PAYLOAD: "INVALID_SIGNAL_PAYLOAD"
} as const;

export type SignalingErrorCode =
  (typeof SIGNALING_ERROR_CODES)[keyof typeof SIGNALING_ERROR_CODES];